package cmd

// byocCmdCase is one resource command invocation with valid arguments.
type byocCmdCase struct {
	name string
	args []string
}

// byocCmdCases enumerates every resource command with a valid,
// hermetic argument set. Shared by the transport-error and
// no-credentials table tests, which run the whole surface against a
// stub that fails at, respectively, the connection and the credential
// stage.
var byocCmdCases = []byocCmdCase{
	{"cluster list", []string{"cluster", "list"}},
	{"cluster get", []string{"cluster", "get", testClusterID}},
	{"cluster create", []string{"cluster", "create", "--name", "c",
		"--cloud-account-id", testClusterID, "--regions", "us-east-1",
		"--node-location", "public"}},
	{"cluster delete",
		[]string{"cluster", "delete", testClusterID, "--force"}},
	{"cluster update", []string{"cluster", "update", testClusterID,
		"--regions", "eu-west-1"}},
	{"cluster share list",
		[]string{"cluster", "share", "list", testClusterID}},
	{"cluster share get",
		[]string{"cluster", "share", "get", testClusterID, testShareID}},
	{"cluster share create",
		[]string{"cluster", "share", "create", testClusterID, "--name", "s"}},
	{"cluster share delete", []string{"cluster", "share", "delete",
		testClusterID, testShareID, "--force"}},
	{"cluster metrics", []string{"cluster", "metrics", testClusterID}},
	{"node list", []string{"node", "list", testClusterID}},
	{"node logs", []string{"node", "logs", testClusterID,
		testNodeID, "postgresql"}},
	{"database list", []string{"database", "list"}},
	{"database get", []string{"database", "get", testDatabaseID}},
	{"database connection-string",
		[]string{"database", "connection-string", testDatabaseID}},
	{"database inspect",
		[]string{"database", "inspect", testDatabaseID, "table-sizes"}},
	{"database create", []string{"database", "create", "--name", "d",
		"--cluster-id", testClusterID}},
	{"database update", []string{"database", "update", testDatabaseID,
		"--display-name", "x"}},
	{"database delete",
		[]string{"database", "delete", testDatabaseID, "--force"}},
	{"database rotate-password", []string{"database",
		"rotate-password", testDatabaseID, "--role", "app", "--force"}},
	{"database restore", []string{"database", "restore", testDatabaseID,
		"--node-name", "n1", "--repository", "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d", "--force"}},
	{"database logs", []string{"database", "logs", testDatabaseID,
		"--component-name", "postgres", "--nodes", "n1"}},
	{"database metrics", []string{"database", "metrics", testDatabaseID}},
	{"database service list",
		[]string{"database", "service", "list", testDatabaseID}},
	{"database service get",
		[]string{"database", "service", "get", testDatabaseID, "svc-1"}},
	{"database service remove", []string{"database", "service",
		"remove", testDatabaseID, "mcp", "--force"}},
	{"database mcp deploy",
		[]string{"database", "mcp", "deploy", testDatabaseID}},
	{"database postgrest deploy", []string{"database", "postgrest",
		"deploy", testDatabaseID, "--db-schemas", "public",
		"--db-anon-role", "web_anon"}},
	{"database rag update", []string{"database", "rag", "update",
		testDatabaseID, "--top-n", "5"}},
	{"backup create", []string{"backup", "create", "--database-id",
		testDatabaseID, "--provider", "pgbackrest"}},
	{"backup-store list", []string{"backup-store", "list"}},
	{"backup-store get", []string{"backup-store", "get", testStoreID}},
	{"backup-store create", []string{"backup-store", "create",
		"--name", "s", "--cloud-account-id", testClusterID}},
	{"backup-store delete",
		[]string{"backup-store", "delete", testStoreID, "--force"}},
	{"cloud-account list", []string{"cloud-account", "list"}},
	{"cloud-account get",
		[]string{"cloud-account", "get", testAccountID}},
	{"cloud-account create",
		[]string{"cloud-account", "create", "--type", "aws",
			"--role-arn", "arn:x"}},
	{"cloud-account delete",
		[]string{"cloud-account", "delete", testAccountID, "--force"}},
	{"cloud-account cf-template",
		[]string{"cloud-account", "cloudformation-template"}},
	{"cloud-account availability-zones", []string{"cloud-account",
		"availability-zones", testAccountID, "--region", "us-east-2"}},
	{"backup-repository list", []string{"backup-repository", "list"}},
	{"backup-repository get", []string{"backup-repository", "get",
		testBackupRepoID, "n1"}},
	{"config-version list", []string{"config-version", "list"}},
	{"config-version get", []string{"config-version", "get", "15.6.0"}},
	{"ingress list", []string{"ingress", "list"}},
	{"ingress get", []string{"ingress", "get", testIngressID}},
	{"ingress create", []string{"ingress", "create", "--name", "web",
		"--cluster-id", testClusterID, "--region", "us-east-1"}},
	{"ingress delete",
		[]string{"ingress", "delete", testIngressID, "--force"}},
	{"ingress service list",
		[]string{"ingress", "service", "list", testIngressID}},
	{"ingress service register", []string{"ingress", "service",
		"register", testIngressID, "--database-id", testDatabaseID,
		"--service-id", "svc-1"}},
	{"ingress service deregister", []string{"ingress", "service",
		"deregister", testIngressID, "svc-1", "--force"}},
	{"ssh-key list", []string{"ssh-key", "list"}},
	{"ssh-key get", []string{"ssh-key", "get", testSSHKeyID}},
	{"ssh-key create", []string{"ssh-key", "create", "--name", "k",
		"--public-key", fixturePublicKey}},
	{"ssh-key delete",
		[]string{"ssh-key", "delete", testSSHKeyID, "--force"}},
	{"task list", []string{"task", "list"}},
	{"task get", []string{"task", "get", "7db8f401-0d8d-4daf-889b-f721e395df61"}},
	{"task wait", []string{"task", "wait", "7db8f401-0d8d-4daf-889b-f721e395df61"}},
}
