# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgedge" do
  version "0.5.0-beta.3-SNAPSHOT-cb52ea8"

  on_macos do
    on_arm do
      sha256 "1e25daaac2bceeeca9b2504bcd7351b2aafb5bb4207a3a52a31a8011c8188b1a"
      url "https://github.com/pgEdge/pgedge-cli/releases/download/v0.5.0-beta.3/pgedge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6c33f916cb8a9d1009816660fdc58244ef995997b9e41cf12e92d73985d0db1f"
      url "https://github.com/pgEdge/pgedge-cli/releases/download/v0.5.0-beta.3/pgedge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "db037ee986bdecf98a6214e2d952e6e3a13dbf1e42517b223f349fcc2e58f755"
      url "https://github.com/pgEdge/pgedge-cli/releases/download/v0.5.0-beta.3/pgedge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b14c0eb751d40f334297e04430c490aec12a1d2b780b05a4a0e64f0bd33bd78"
      url "https://github.com/pgEdge/pgedge-cli/releases/download/v0.5.0-beta.3/pgedge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pgedge"
  desc "Unified CLI for the pgEdge product suite"
  homepage "https://github.com/pgEdge/pgedge-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgedge"
  bash_completion "completions/pgedge.bash"
  fish_completion "completions/pgedge.fish"
  zsh_completion "completions/pgedge.zsh"

  # No zap stanza required
end
