# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgedge" do
  version "0.5.0-beta.3"

  on_macos do
    on_arm do
      sha256 "ab7cd19b1d61410de35108c206776712aee9130b882973473d4bc466e51b38d4"
      url "https://github.com/pgEdge/pgedge-cli/releases/download/v#{version}/pgedge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "df490273f26357a097116d22065ebbbda9071e97ad8b4b49d3511a53351ae606"
      url "https://github.com/pgEdge/pgedge-cli/releases/download/v#{version}/pgedge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4debdf36ce0bd082fd90bd65d2a2a500b1c04a9196ea61db8a825c36d0652ebe"
      url "https://github.com/pgEdge/pgedge-cli/releases/download/v#{version}/pgedge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7885c816221fbb17a1402319ef7e870e56414c01688d49d6bcc7c9694cfdf699"
      url "https://github.com/pgEdge/pgedge-cli/releases/download/v#{version}/pgedge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pgedge"
  desc "Unified CLI for the pgEdge product suite"
  homepage "https://github.com/pgEdge/pgedge-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgedge"
  bash_completion "completions/pgedge.bash"
  fish_completion "completions/pgedge.fish"
  zsh_completion "completions/pgedge.zsh"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args:           ["-dr", "com.apple.quarantine", "pgedge"],
          chdir:          ".",
          writable_paths: ["pgedge"]
    end
  end

  # No zap stanza required
end
