package cli

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"

	"github.com/pgEdge/pgedge-cli/internal/module"
	"github.com/pgEdge/pgedge-cli/internal/output"
	"github.com/pgEdge/pgedge-cli/internal/selfupdate"
)

// completionShells is every shell `completion install` can write for,
// in the order the refresh reports them.
var completionShells = []string{"bash", "zsh", "fish", "powershell"}

// refreshCompletions rewrites each completion script found where
// `completion install` puts one, generated by the new binary at target,
// since this process's own cobra tree is the release being replaced. A
// shell with no script installed is left alone; nothing is ever created.
// Failures warn on stderr and never fail the command: the swap has
// already succeeded, and a stale script is where the user started.
func refreshCompletions(
	rt *module.Runtime, runner selfupdate.Runner, target string,
) {
	home, err := os.UserHomeDir()
	if err != nil {
		fmt.Fprintf(rt.Stderr,
			"warning: could not refresh shell completions: %s\n",
			output.Sanitize(err.Error()))
		return
	}
	for _, shell := range completionShells {
		path, ok := installedCompletionPath(home, shell)
		if !ok {
			continue
		}
		if err := regenerateCompletion(runner, target, shell, path); err != nil {
			fmt.Fprintf(rt.Stderr,
				"warning: could not refresh %s completion at %s: %s\n",
				output.Sanitize(shell),
				output.Sanitize(displayPath(path, home)),
				output.Sanitize(err.Error()))
			continue
		}
		fmt.Fprintf(rt.Stderr, "refreshed %s completion (%s)\n",
			output.Sanitize(shell), output.Sanitize(displayPath(path, home)))
	}
}

// installedCompletionPath reports where shell's completion script
// lives and whether one is installed there.
func installedCompletionPath(home, shell string) (string, bool) {
	var path string
	if shell == "powershell" {
		_, path, _, _ = pwshScriptPath(home)
	} else {
		_, path = completionScriptPath(home, shell)
	}
	if path == "" {
		return "", false
	}
	if _, err := os.Stat(path); err != nil {
		return "", false
	}
	return path, true
}

// regenerateCompletion execs `<target> completion <shell>` and
// replaces the script at path with its output. The script is staged
// beside path and renamed into place, so a shell that starts
// mid-write sources the old script or the new one, never a torn one.
func regenerateCompletion(
	runner selfupdate.Runner, target, shell, path string,
) error {
	ctx, cancel := context.WithTimeout(
		context.Background(), selfupdate.ProbeTimeout)
	defer cancel()

	cmd := runner(ctx, target, "completion", shell)
	var stdout bytes.Buffer
	cmd.Stdout = &stdout
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("generate script: %w", err)
	}
	if stdout.Len() == 0 {
		return errors.New("generate script: the new binary printed nothing")
	}

	staged := path + ".new"
	if err := os.WriteFile(staged, stdout.Bytes(), 0o600); err != nil {
		return err
	}
	if err := os.Rename(staged, path); err != nil {
		_ = os.Remove(staged)
		return err
	}
	return nil
}
